### ISSUE TITLE
Post category ancestor retrieves no values

### ISSUE THREAD

**Issue by dasheck0** [billerickson/acf-location-rules#1]
Hi,

I just installed your plugin for showing the custom fields only when the post is within a category descending from a selected category (aka Post Category Ancestor).

However the 'acf/location/rule_values/*' does not seem to work as I get no values in the rule values box. Is the plugin broken or did I do something wrong?

Thanks and best regards
dasheck

**Comment by billerickson** [comment]
I recommend you submit your issue to Advanced Custom Fields.  I haven't used it in a while so am not aware of any potential changes to their code.  

The code in this repo worked for me about a year ago.
